//! VeloEngine: The Orchestration Layer
//!
//! This module defines the `VeloEngine`, which is the "brain" of the inference stack.
//! It coordinates three major components:
//! 1. **RadixCache**: A prefix-matching cache that reuses the "memory" of past prompts.
//! 2. **MemoryRuntime**: The actual storage for KV-blocks (either in CPU memory or GPU VRAM).
//! 3. **SpeculativeDecoder**: The logic that guesses future tokens to speed up generation.
//!
//! ### Key Concepts for Beginners:
//! - **Tokens**: LLMs don't read words; they read numbers called "tokens".
//! - **KV-Cache**: LLMs have a "short-term memory" called the Key-Value cache. It stores
//!   the context of the conversation so the model doesn't have to re-read everything every time.
//! - **Slots**: Think of a "slot" as a workspace for a single request. If the engine has 4 slots,
//!   it can handle 4 people chatting with it at the exact same time.
//! - **Prefill**: The very first step where the model reads your prompt.
//! - **Decoding**: The step-by-step process of generating new words.

use crate::kv_store::KvStoreError;
use crate::paged_attention::{PageManagerError, PageSpan, KvCacheType};
use crate::radix_cache::{CacheLookup, KvCacheHandle, RadixCache, TokenId};
use crate::runtime::{
    CpuMemoryRuntime, KvBlockStore, MemoryRuntime, MemoryRuntimeConfig, PagedBlockAllocator,
};
use crate::speculative::{
    SpeculativeDecoder, SpeculativeError, SpeculativeStats,
};



/// High-performance inference engine for speculative decoding.
///
/// `VeloEngine` orchestrates the radix-prefix cache, paged-attention memory,
/// and the speculative draft/verify loop. It uses a `SlotPool` to isolate
/// concurrent requests and provide stable indexing for GPU backends.
pub struct VeloEngine<R = CpuMemoryRuntime> {
    /// Orchestrates the draft-and-verify speculative loop.
    decoder: SpeculativeDecoder,
    /// Manages prefix KV-cache reuse and eviction.
    prefix_cache: RadixCache,
    /// Backend-specific memory and execution runtime (CPU or Metal).
    runtime: R,
    /// Pool of stable indexes (slots) for concurrent request state.
    slot_pool: crate::slot_manager::SlotPool,
    /// Factory for creating grammar matchers (used for structured JSON/Regex output).
    pub parser_factory: Option<std::sync::Arc<llguidance::ParserFactory>>,
}

impl<R> std::fmt::Debug for VeloEngine<R> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VeloEngine")
            .field("decoder", &self.decoder)
            .field("prefix_cache", &self.prefix_cache)
            .field("slot_pool", &self.slot_pool)
            .finish()
    }
}

/// Global configuration for the inference engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EngineConfig {
    /// Number of tokens to "guess" per speculative step. Higher = more potential speed, but more GPU work.
    pub draft_window: usize,
    /// Memory limits and resource configuration (how many slots, how much cache).
    pub memory: MemoryRuntimeConfig,
    /// Numerical precision for the KV-cache (e.g. FP32 for accuracy, INT8 for memory savings).
    pub kv_type: KvCacheType,
}

impl Default for EngineConfig {
    fn default() -> Self {
        Self {
            draft_window: 8,
            memory: MemoryRuntimeConfig::default(),
            kv_type: KvCacheType::Fp32,
        }
    }
}

/// The result of a single generation request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EngineOutput {
    /// The actual tokens generated by the model.
    pub tokens: Vec<TokenId>,
    /// Information about how much of the prompt was found in the prefix cache.
    pub cached_prefix: CacheLookup,
    /// Memory pages used from the existing cache.
    pub cached_pages: Option<PageSpan>,
    /// Handle for the newly generated sequence in the cache.
    pub inserted_handle: Option<KvCacheHandle>,
    /// Memory pages allocated for the new generation.
    pub inserted_pages: Option<PageSpan>,
    /// Statistics about the generation (tokens per second, cache hits, etc).
    pub stats: EngineStats,
}

/// A request to be processed by the engine.
#[derive(Debug, Clone)]
pub struct BatchRequest {
    /// The prompt tokens to process.
    pub prompt: Vec<TokenId>,
    /// Maximum number of new tokens to generate before stopping.
    pub max_new_tokens: usize,
    /// Optional structured output constraint (JSON schema, regex, or CFG).
    pub constraint: Option<crate::constraints::Constraint>,
}

/// Internal state for a request currently being processed in a batch.
/// This tracks the progress of a single chat session inside the engine.
pub struct ActiveRequest {
    /// The speculative decoding session (tracks draft/verify progress).
    pub session: crate::speculative::SpeculativeSession,
    /// The GPU slot assigned to this request (its workspace).
    pub slot_id: crate::slot_manager::SlotId,
    /// Maximum number of new tokens to generate.
    pub max_new_tokens: usize,
    /// Tokens generated so far in this session.
    pub generated: Vec<TokenId>,
    /// Results from the initial "prefill" phase.
    pub prefill: EnginePrefillOutput,
    /// Optional grammar matcher for constrained decoding (e.g. valid JSON).
    pub matcher: Option<Box<dyn crate::constraints::CfgMatcher>>,
}

/// Results from the initial "prefill" (reading the prompt) phase.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnginePrefillOutput {
    pub cached_prefix: CacheLookup,
    pub cached_pages: Option<PageSpan>,
    pub inserted_handle: Option<KvCacheHandle>,
    pub inserted_pages: Option<PageSpan>,
    pub stats: EngineStats,
}

/// Real-time statistics about the engine's performance.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct EngineStats {
    /// How many tokens were reused from the cache (saved time!).
    pub cache_hit_tokens: usize,
    /// How many tokens had to be calculated from scratch.
    pub cache_miss_tokens: usize,
    /// Detailed stats for the speculative decoding loop.
    pub speculative: SpeculativeStats,
}

/// Potential errors that can occur during inference.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineError {
    /// Error in the low-level KV storage.
    KvStore(KvStoreError),
    /// Error in memory page management.
    PagedAttention(PageManagerError),
    /// Error in the speculative decoding logic.
    Speculative(SpeculativeError),
}

impl VeloEngine {
    pub fn new(config: EngineConfig) -> Result<Self, EngineError> {
        let runtime = CpuMemoryRuntime::new(config.memory)?;

        Self::with_runtime(config, runtime)
    }
}

impl<R> VeloEngine<R>
where
    R: MemoryRuntime,
{
    /// Starts the engine with a specific hardware runtime (like Metal for GPU).
    pub fn with_runtime(config: EngineConfig, runtime: R) -> Result<Self, EngineError> {
        Ok(Self {
            decoder: SpeculativeDecoder::new(config.draft_window)?,
            prefix_cache: RadixCache::new(),
            slot_pool: crate::slot_manager::SlotPool::new(config.memory.max_slots),
            runtime,
            parser_factory: None,
        })
    }

    /// Access the speculative decoder (the logic for guessing tokens).
    pub fn decoder(&self) -> &SpeculativeDecoder {
        &self.decoder
    }

    /// How many concurrent requests this engine can handle.
    pub fn slot_pool_capacity(&self) -> usize {
        self.slot_pool.capacity()
    }

    /// Reserves a workspace (slot) for a new request.
    pub fn allocate_slot(&mut self) -> Option<crate::slot_manager::SlotId> {
        self.slot_pool.alloc()
    }

    /// Frees up a workspace (slot) once a request is finished.
    pub fn release_slot(&mut self, slot_id: crate::slot_manager::SlotId) {
        self.slot_pool.release(slot_id);
    }

    /// Single-request generation helper.
    /// This is the easiest way to ask the model to generate text.
    pub fn generate<D, T>(
        &mut self,
        draft_model: &mut D,
        target_model: &mut T,
        prompt: &[TokenId],
        max_new_tokens: usize,
    ) -> Result<EngineOutput, EngineError>
    where
        D: crate::speculative::DraftModel,
        T: crate::speculative::TargetModel,
    {
        let outputs = self.generate_batch(
            draft_model,
            target_model,
            vec![BatchRequest {
                prompt: prompt.to_vec(),
                max_new_tokens,
                constraint: None,
            }],
        )?;

        Ok(outputs.into_iter().next().unwrap())
    }

    /// Generates tokens for multiple requests at the same time!
    ///
    /// This is the most complex part of the engine. It runs a loop that:
    /// 1. **Drafts**: A small, fast model "guesses" the next few tokens.
    /// 2. **Verifies**: A large, accurate model checks those guesses.
    /// 3. **Commits**: Only the correct guesses are kept, and the process repeats.
    ///
    /// By doing this in a "batch", we can process multiple people's requests in one GPU pass.
    pub fn generate_batch<D, T>(
        &mut self,
        draft_model: &mut D,
        target_model: &mut T,
        requests: Vec<BatchRequest>,
    ) -> Result<Vec<EngineOutput>, EngineError>
    where
        D: crate::speculative::DraftModel,
        T: crate::speculative::TargetModel,
    {
        let mut active = Vec::with_capacity(requests.len());

        // Step A: Prepare each request in the batch.
        for req in requests {
            // 1. Get a workspace (slot) for this request.
            let slot_id = self.slot_pool.alloc().ok_or_else(|| {
                EngineError::Speculative(crate::speculative::SpeculativeError::Model(
                    "No free slots available".to_string(),
                ))
            })?;

            // 2. Prefill: Have the model read the prompt and see if we can reuse past memory.
            let prefill = self.prefill(&req.prompt)?;
            let pages = prefill
                .inserted_pages
                .as_ref()
                .or(prefill.cached_pages.as_ref())
                .ok_or_else(|| {
                    EngineError::Speculative(crate::speculative::SpeculativeError::Model(
                        "Failed to resolve pages for prefill".to_string(),
                    ))
                })?;

            // 3. Bind the memory pages to the GPU slot so the backend knows where to look.
            let page_ids: Vec<u32> = pages.pages.iter().map(|p| p.0 as u32).collect();
            self.runtime.bind_slot(slot_id, &page_ids)?;

            // 4. Start a "session" to track how many tokens we've generated.
            let session = self.decoder.begin(&req.prompt)?;

            // 5. (Optional) Set up a grammar matcher if the user wants JSON or a specific format.
            let mut matcher = if let Some(constraint) = req.constraint {
                 if let Some(factory) = &self.parser_factory {
                    let grammar = match constraint {
                        crate::constraints::Constraint::Regex(r) => llguidance::api::TopLevelGrammar::from_regex(&r),
                        crate::constraints::Constraint::JsonSchema(j) => llguidance::api::TopLevelGrammar::from_json_schema(j),
                        crate::constraints::Constraint::Lark(l) => llguidance::api::TopLevelGrammar::from_lark(l),
                    };
                    let vocab_size = factory.tok_env().tok_trie().vocab_size() as usize;
                    match crate::constraints::LlguidanceMatcher::new(factory, grammar, vocab_size) {
                        Ok(m) => Some(Box::new(m) as Box<dyn crate::constraints::CfgMatcher>),
                        Err(e) => {
                            eprintln!("Failed to create LlguidanceMatcher: {}", e);
                            None
                        }
                    }
                 } else {
                    eprintln!("No parser_factory found in engine");
                    None
                 }
            } else {
                None
            };

            if let Some(m) = matcher.as_mut() {
                for &token in &req.prompt {
                    m.advance(token);
                }
            }

            active.push(ActiveRequest {
                session,
                slot_id,
                max_new_tokens: req.max_new_tokens,
                generated: Vec::new(),
                prefill,
                matcher,
            });
        }

        // Bind prefix caches before starting
        for req in &mut active {
            draft_model.bind_slot(req.slot_id)?;
            target_model.bind_slot(req.slot_id)?;
            draft_model.bind_prefix_cache(&req.prefill.cached_prefix)?;
            target_model.bind_prefix_cache(&req.prefill.cached_prefix)?;
        }

        // Step B: The main generation loop.
        // We keep running as long as at least one request still needs more tokens.
        while active.iter().any(|req| req.generated.len() < req.max_new_tokens) {
            let active_indices: Vec<usize> = active
                .iter()
                .enumerate()
                .filter(|(_, req)| req.generated.len() < req.max_new_tokens)
                .map(|(i, _)| i)
                .collect();

            if active_indices.is_empty() {
                break;
            }

            // 1. DRAFT PHASE: The fast model makes "guesses".
            let draft_results = {
                let mut draft_matchers: Vec<Option<Box<dyn crate::constraints::CfgMatcher>>> = active
                    .iter()
                    .map(|req| req.matcher.as_ref().map(|m| m.clone_box()))
                    .collect();

                let mut draft_reqs: Vec<(&[TokenId], usize, Option<&mut (dyn crate::constraints::CfgMatcher + '_)>)> = active
                    .iter_mut()
                    .zip(draft_matchers.iter_mut())
                    .filter(|(req, _)| req.generated.len() < req.max_new_tokens)
                    .map(|(req, matcher)| {
                        let remaining = req.max_new_tokens - req.generated.len();
                        let requested = remaining.min(self.decoder.draft_window());
                        (req.session.context(), requested, matcher.as_deref_mut())
                    })
                    .collect();

                draft_model.draft_batch(&mut draft_reqs)?
            };

            for &idx in &active_indices {
                active[idx].session.record_draft_call();
            }

            // 2. VERIFY PHASE: The large model checks all the guesses in one go.
            let mut drafted_tokens_storage = Vec::with_capacity(active_indices.len());
            for i in 0..active_indices.len() {
                let drafted_tokens: Vec<TokenId> =
                    draft_results[i].iter().map(|p| p.token).collect();
                drafted_tokens_storage.push(drafted_tokens);
            }

            let verify_results = {
                let mut verify_reqs: Vec<(&[TokenId], &[TokenId], Option<&mut (dyn crate::constraints::CfgMatcher + '_)>)> = active
                    .iter_mut()
                    .enumerate()
                    .filter(|(_, req)| req.generated.len() < req.max_new_tokens)
                    .enumerate()
                    .map(|(batch_idx, (_, req))| {
                        (req.session.context(), drafted_tokens_storage[batch_idx].as_slice(), req.matcher.as_deref_mut())
                    })
                    .collect();

                target_model.verify_batch(&mut verify_reqs)?
            };

            for &idx in &active_indices {
                active[idx].session.record_target_call();
            }

            // 3. COMMIT PHASE: Keep the correct guesses and discard the wrong ones.
            for (i, &idx) in active_indices.iter().enumerate() {
                let req = &mut active[idx];
                let accepted = req.session.commit(&draft_results[i], &verify_results[i])?;
                req.generated.extend_from_slice(&accepted);

                // If the target model disagreed with a guess, it provides a "correct" token to get back on track.
                if req.session.has_pending_rejection() {
                    if let Some(token) = req.session.take_rejected_token() {
                        req.generated.push(token);
                    }
                }
            }
        }

        // Step C: Wrap up and save the new tokens to the cache for next time.
        let mut final_outputs = Vec::with_capacity(active.len());
        for req in active {
            self.slot_pool.release(req.slot_id);

            let mut full_sequence = Vec::with_capacity(req.session.prompt().len() + req.generated.len());
            full_sequence.extend_from_slice(req.session.prompt());
            full_sequence.extend_from_slice(&req.generated);

            let inserted_handle = if !full_sequence.is_empty() {
                Some(self.cache_sequence(&full_sequence)?)
            } else {
                None
            };

            final_outputs.push(EngineOutput {
                tokens: req.generated,
                cached_prefix: req.prefill.cached_prefix,
                cached_pages: req.prefill.cached_pages,
                inserted_handle,
                inserted_pages: inserted_handle
                    .and_then(|handle| self.runtime.allocator().materialize_span(handle)),
                stats: EngineStats {
                    cache_hit_tokens: req.prefill.stats.cache_hit_tokens,
                    cache_miss_tokens: req.prefill.stats.cache_miss_tokens,
                    speculative: req.session.stats().clone(),
                },
            });
        }

        Ok(final_outputs)
    }

    /// Prefill: The engine "reads" the prompt before generating text.
    /// It checks the `RadixCache` to see if it has already processed this prompt (or part of it) before.
    pub fn prefill(&mut self, prompt: &[TokenId]) -> Result<EnginePrefillOutput, EngineError> {
        let cached_prefix = self.prefix_cache.lookup(prompt);
        let inserted_handle = if !prompt.is_empty() && cached_prefix.matched_tokens < prompt.len() {
            // If we didn't find the whole prompt in the cache, we save it now.
            Some(self.cache_sequence(prompt)?)
        } else {
            None
        };

        Ok(EnginePrefillOutput {
            cached_pages: cached_prefix
                .handle
                .and_then(|handle| self.runtime.allocator().materialize_span(handle)),
            inserted_pages: inserted_handle
                .and_then(|handle| self.runtime.allocator().materialize_span(handle)),
            stats: EngineStats {
                cache_hit_tokens: cached_prefix.matched_tokens,
                cache_miss_tokens: prompt.len() - cached_prefix.matched_tokens,
                speculative: SpeculativeStats::default(),
            },
            cached_prefix,
            inserted_handle,
        })
    }

    pub fn cache(&self) -> &RadixCache {
        &self.prefix_cache
    }

    pub fn cache_mut(&mut self) -> &mut RadixCache {
        &mut self.prefix_cache
    }

    pub fn runtime(&self) -> &R {
        &self.runtime
    }

    pub fn runtime_mut(&mut self) -> &mut R {
        &mut self.runtime
    }

    /// Internal helper to save a sequence of tokens into the KV-cache.
    fn cache_sequence(&mut self, tokens: &[TokenId]) -> Result<KvCacheHandle, EngineError> {
        // 1. Ask the backend to find a spot in memory.
        let handle = self.runtime.store_mut().allocate(tokens.len())?;
        if let Err(error) = self.runtime.allocator_mut().allocate(handle, tokens.len()) {
            self.runtime.store_mut().release(handle)?;
            return Err(error.into());
        }

        // 2. Add it to the radix tree so we can find it later.
        let inserted = self.prefix_cache.insert(tokens, handle);
        if let Some(replaced) = inserted.replaced {
            // If we replaced an old cache entry, free its memory.
            self.runtime.store_mut().release(replaced)?;
            self.runtime.allocator_mut().release(replaced)?;
        }
        Ok(handle)
    }
}

impl From<KvStoreError> for EngineError {
    fn from(error: KvStoreError) -> Self {
        Self::KvStore(error)
    }
}

impl From<PageManagerError> for EngineError {
    fn from(error: PageManagerError) -> Self {
        Self::PagedAttention(error)
    }
}

impl From<SpeculativeError> for EngineError {
    fn from(error: SpeculativeError) -> Self {
        Self::Speculative(error)
    }
}

impl std::fmt::Display for EngineError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::KvStore(error) => write!(formatter, "KV store failed: {error}"),
            Self::PagedAttention(error) => write!(formatter, "paged attention failed: {error}"),
            Self::Speculative(error) => write!(formatter, "speculative decoding failed: {error}"),
        }
    }
}

impl std::error::Error for EngineError {}

impl VeloEngine<CpuMemoryRuntime> {
    pub fn kv_store(&self) -> &crate::kv_store::InMemoryKvStore {
        self.runtime.store()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::radix_cache::KvCacheHandle;
    use crate::paged_attention::KvCacheType;
    use crate::kv_store::KvStore;
    use crate::metal::Quantization;
    use crate::{MetalMemoryRuntime, MetalRuntimeConfig};
    use crate::speculative::{
        DraftModel, NextTokenPrediction, Result as SpeculativeResult, TargetModel, VerifyStep,
    };

    /// THE TEST "ACTORS" (Mocks)
    /// 
    /// To test the engine without needing a real AI model or a GPU, 
    /// we create "Scripted" versions of models.
    /// Think of these like actors in a play who just read from a script we give them.

    #[derive(Debug)]
    struct ScriptedDraft {
        /// The list of tokens this "assistant" will guess.
        script: Vec<TokenId>,
        bound_prefixes: Vec<CacheLookup>,
        bound_slots: Vec<crate::slot_manager::SlotId>,
    }

    impl DraftModel for ScriptedDraft {
        fn bind_prefix_cache(&mut self, prefix: &CacheLookup) -> SpeculativeResult<()> {
            self.bound_prefixes.push(prefix.clone());
            Ok(())
        }

        fn bind_slot(&mut self, slot: crate::slot_manager::SlotId) -> SpeculativeResult<()> {
            self.bound_slots.push(slot);
            Ok(())
        }

        fn draft(
            &mut self,
            context: &[TokenId],
            max_tokens: usize,
            _matcher: Option<&mut (dyn crate::constraints::CfgMatcher + '_)>,
        ) -> SpeculativeResult<Vec<NextTokenPrediction>> {
            // Just return tokens from the script starting from where the context ends.
            Ok(self.script[context.len()..]
                .iter()
                .take(max_tokens)
                .map(|token| NextTokenPrediction {
                    token: *token,
                    confidence: 1.0,
                })
                .collect())
        }
    }

    #[derive(Debug)]
    struct ScriptedTarget {
        /// The list of tokens the "editor" will verify against.
        script: Vec<TokenId>,
        bound_prefixes: Vec<CacheLookup>,
        bound_slots: Vec<crate::slot_manager::SlotId>,
    }

    impl TargetModel for ScriptedTarget {
        fn bind_prefix_cache(&mut self, prefix: &CacheLookup) -> SpeculativeResult<()> {
            self.bound_prefixes.push(prefix.clone());
            Ok(())
        }

        fn bind_slot(&mut self, slot: crate::slot_manager::SlotId) -> SpeculativeResult<()> {
            self.bound_slots.push(slot);
            Ok(())
        }

        fn verify(
            &mut self,
            context: &[TokenId],
            drafted: &[TokenId],
            _matcher: Option<&mut (dyn crate::constraints::CfgMatcher + '_)>,
        ) -> SpeculativeResult<Vec<VerifyStep>> {
            // Check the drafted tokens against the "Ground Truth" in the script.
            Ok(self.script[context.len()..]
                .iter()
                .take(drafted.len())
                .map(|token| VerifyStep { expected: *token })
                .collect())
        }
    }

    #[test]
    fn generates_and_caches_full_sequence() {
        // TEST: Basic End-to-End Generation
        // 1. We provide a prompt [10, 20].
        // 2. The assistant guesses [30, 40].
        // 3. The editor agrees.
        // 4. We check if the final result is correct and saved to the cache.
        
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 4,
            memory: MemoryRuntimeConfig::cpu(128, 16, 32, 32, 32),
            kv_type: KvCacheType::Fp32,
        })
        .unwrap();
        let prompt = [10, 20];
        let mut draft = ScriptedDraft {
            script: vec![10, 20, 30, 40],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![10, 20, 30, 40],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        let output = engine
            .generate(&mut draft, &mut target, &prompt, 2)
            .unwrap();

        assert_eq!(output.tokens, vec![30, 40]);
        assert_eq!(output.cached_prefix.matched_tokens, 0); // First time, so no cache hit
        assert!(output.inserted_pages.is_some());
        
        // Check if it's in the cache for next time.
        assert_eq!(
            engine.cache_mut().lookup(&[10, 20, 30, 40]).matched_tokens,
            4
        );
    }

    #[test]
    fn reports_cache_hit_for_repeated_prompt_prefix() {
        // TEST: The "Memory" (Cache) works
        // If we ask the same thing twice, the second time should be faster
        // because the engine "remembers" the first part.
        
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 2,
            memory: MemoryRuntimeConfig::cpu(128, 16, 32, 32, 32),
            kv_type: KvCacheType::Fp32,
        })
        .unwrap();
        
        let mut draft = ScriptedDraft { script: vec![1, 2, 3, 4, 5], bound_prefixes: Vec::new(), bound_slots: Vec::new() };
        let mut target = ScriptedTarget { script: vec![1, 2, 3, 4, 5], bound_prefixes: Vec::new(), bound_slots: Vec::new() };

        // Round 1: Generate something.
        engine.generate(&mut draft, &mut target, &[1, 2], 2).unwrap();

        // Round 2: Ask something that starts with the same tokens.
        let output = engine
            .generate(&mut draft, &mut target, &[1, 2, 3, 4], 1)
            .unwrap();

        // It should find [1, 2, 3, 4] in the cache!
        assert_eq!(output.cached_prefix.matched_tokens, 4);
        assert_eq!(output.stats.cache_hit_tokens, 4);
        assert_eq!(output.tokens, vec![5]);
    }

    #[test]
    fn releases_replaced_kv_block_for_same_sequence() {
        // TEST: Memory Management
        // If we generate the same sequence again, we should replace the old one
        // and free its memory so we don't leak VRAM.
        
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 2,
            memory: MemoryRuntimeConfig::cpu(32, 8, 16, 32, 32),
            kv_type: KvCacheType::Fp32,
        })
        .unwrap();
        
        let mut draft = ScriptedDraft { script: vec![1, 2, 3], bound_prefixes: Vec::new(), bound_slots: Vec::new() };
        let mut target = ScriptedTarget { script: vec![1, 2, 3], bound_prefixes: Vec::new(), bound_slots: Vec::new() };

        let first = engine.generate(&mut draft, &mut target, &[1], 2).unwrap();
        let second = engine.generate(&mut draft, &mut target, &[1], 2).unwrap();

        assert_eq!(first.inserted_handle.unwrap().block_id, 2);
        assert_eq!(second.inserted_handle.unwrap().block_id, 3);
        
        // Even though we generated twice, the cache size should be stable.
        assert_eq!(engine.kv_store().len(), 2); 
    }

    #[test]
    fn binds_cached_prefix_to_both_models_before_generation() {
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 2,
            memory: MemoryRuntimeConfig::cpu(16, 8, 16, 32, 32),
            kv_type: KvCacheType::Fp32,
        })
        .unwrap();
        let mut draft = ScriptedDraft {
            script: vec![7, 8, 9],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![7, 8, 9],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        engine.generate(&mut draft, &mut target, &[7], 2).unwrap();

        let mut draft = ScriptedDraft {
            script: vec![7, 8, 9, 10],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![7, 8, 9, 10],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        engine
            .generate(&mut draft, &mut target, &[7, 8, 9], 1)
            .unwrap();

        assert_eq!(draft.bound_prefixes.len(), 1);
        assert_eq!(target.bound_prefixes.len(), 1);
        assert_eq!(draft.bound_prefixes[0].matched_tokens, 3);
        assert_eq!(target.bound_prefixes[0].matched_tokens, 3);
        assert!(draft.bound_prefixes[0].handle.is_some());
        assert_eq!(draft.bound_prefixes[0], target.bound_prefixes[0]);
    }

    #[test]
    fn can_generate_over_placeholder_metal_runtime() {
        let Ok(runtime) = MetalMemoryRuntime::new(MetalRuntimeConfig {
            model_name: "draft-1b".to_string(),
            memory: MemoryRuntimeConfig::new(32, 8, 16, 32, 32),
            quantization: Quantization::Q4K,
            tensor_parallel_degree: 1,
        }) else {
            // Skip if Metal device not found in test environment
            return;
        };
        let mut engine = VeloEngine::with_runtime(
            EngineConfig {
                draft_window: 2,
                memory: runtime.context().memory,
                kv_type: KvCacheType::Fp32,
            },
            runtime,
        )
        .unwrap();
        let mut draft = ScriptedDraft {
            script: vec![1, 2, 3, 4],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![1, 2, 3, 4],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        let output = engine.generate(&mut draft, &mut target, &[1], 2).unwrap();

        assert_eq!(output.tokens, vec![2, 3]);
        assert_eq!(engine.runtime().context().placement, crate::metal::MetalBufferPlacement::Unified);
        assert_eq!(engine.runtime().store().allocated_bytes(), 128);
        assert_eq!(draft.bound_slots.len(), 1);
        assert_eq!(target.bound_slots.len(), 1);
    }

    #[test]
    fn test_slot_exhaustion() {
        // TEST: Busy Engine
        // If the engine only has 1 workspace (slot), it should only be able
        // to handle one request at a time. However, once the first request 
        // is done, that slot should be freed up for the next person.
        
        let config = EngineConfig {
            draft_window: 4,
            memory: MemoryRuntimeConfig::cpu(128, 16, 32, 1, 1), // Only 1 slot!
            kv_type: KvCacheType::Fp32,
        };
        let mut engine = VeloEngine::new(config).unwrap();
        let mut draft = ScriptedDraft { script: vec![1, 2, 3, 4], bound_prefixes: Vec::new(), bound_slots: Vec::new() };
        let mut target = ScriptedTarget { script: vec![1, 2, 3, 4], bound_prefixes: Vec::new(), bound_slots: Vec::new() };

        // First one works.
        let _ = engine.generate(&mut draft, &mut target, &[1], 2).unwrap();
       
        // Second one ALSO works because the first one finished and "left the garage".
        let _ = engine.generate(&mut draft, &mut target, &[1], 2).unwrap();
       
        assert_eq!(draft.bound_slots.len(), 2);
    }

    #[test]
    fn test_multi_request_batching() {
        // TEST: Parallel Processing (The "Magic" of Batching)
        // Here we simulate TWO different people asking TWO different questions.
        // The engine should be able to process both of them in the same generation loop.
        
        let config = EngineConfig {
            draft_window: 2,
            memory: MemoryRuntimeConfig::cpu(1024, 16, 32, 4, 4), // 4 slots available
            kv_type: KvCacheType::Fp32,
        };
        let mut engine = VeloEngine::new(config).unwrap();

        // Req 1 wants to generate [2, 3]
        // Req 2 wants to generate [11, 12, 13]
        let mut draft = ScriptedDraft {
            script: vec![0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 13],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        let mut target = ScriptedTarget {
            script: vec![0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 13],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        
        // Submit both requests at once!
        let requests = vec![
            BatchRequest { prompt: vec![0], max_new_tokens: 2, constraint: None },
            BatchRequest { prompt: vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], max_new_tokens: 3, constraint: None },
        ];

        let results = engine.generate_batch(&mut draft, &mut target, requests).unwrap();

        assert_eq!(results.len(), 2);
        assert_eq!(results[0].tokens, vec![2, 3]);
        assert_eq!(results[1].tokens, vec![11, 12, 13]);

        // Verify isolation: both slots were used
        assert_eq!(draft.bound_slots.len(), 2);
        assert_ne!(draft.bound_slots[0], draft.bound_slots[1]);
    }

    #[test]
    fn test_batch_with_mixed_finishing() {
        let config = EngineConfig {
            draft_window: 1,
            memory: MemoryRuntimeConfig::cpu(1024, 16, 32, 4, 4),
            kv_type: KvCacheType::Fp32,
        };
        let mut engine = VeloEngine::new(config).unwrap();

        // Req 1: generates [2] (stops at max_tokens=1)
        // Req 2: generates [11, 12] (stops at max_tokens=2)
        let mut draft = ScriptedDraft {
            script: vec![0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        let requests = vec![
            BatchRequest {
                prompt: vec![1],
                max_new_tokens: 1,
                constraint: None,
            },
            BatchRequest {
                prompt: vec![10; 11],
                max_new_tokens: 2,
                constraint: None,
            },
        ];

        let outputs = engine.generate_batch(&mut draft, &mut target, requests).unwrap();

        assert_eq!(outputs[0].tokens, vec![2]);
        assert_eq!(outputs[1].tokens, vec![11, 12]);
    }

    #[test]
    fn test_batch_slot_exhaustion() {
        let config = EngineConfig {
            draft_window: 1,
            memory: MemoryRuntimeConfig::cpu(1024, 16, 32, 1, 1), // Only 1 slot
            kv_type: KvCacheType::Fp32,
        };
        let mut engine = VeloEngine::new(config).unwrap();
        let mut draft = ScriptedDraft {
            script: vec![1, 2],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };
        let mut target = ScriptedTarget {
            script: vec![1, 2],
            bound_prefixes: Vec::new(),
            bound_slots: Vec::new(),
        };

        let requests = vec![
            BatchRequest {
                prompt: vec![0],
                max_new_tokens: 1,
                constraint: None,
            },
            BatchRequest {
                prompt: vec![0],
                max_new_tokens: 1,
                constraint: None,
            },
        ];

        let result = engine.generate_batch(&mut draft, &mut target, requests);
        assert!(result.is_err());
    }

    #[test]
    fn engine_error_display() {
        assert!(format!("{}", EngineError::Speculative(SpeculativeError::EmptyDraftWindow)).contains("speculative decoding failed"));
        assert!(format!("{}", EngineError::KvStore(KvStoreError::EmptyBlock)).contains("KV store failed"));
        assert!(format!("{}", EngineError::PagedAttention(PageManagerError::InvalidBlockSize)).contains("paged attention failed"));
    }

    #[test]
    fn engine_accessors_and_stats() {
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 1,
            memory: MemoryRuntimeConfig::cpu(16, 16, 32, 1, 32),
            kv_type: KvCacheType::Fp32,
        }).unwrap();
       
        assert_eq!(engine.cache().len(), 0);
        assert_eq!(engine.cache_mut().len(), 0);
       
        let stats = EngineStats::default();
        assert_eq!(stats.cache_hit_tokens, 0);
    }

    #[test]
    fn prefill_empty_prompt() {
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 1,
            memory: MemoryRuntimeConfig::cpu(16, 16, 32, 1, 32),
            kv_type: KvCacheType::Fp32,
        }).unwrap();
        let prefill = engine.prefill(&[]).unwrap();
        assert_eq!(prefill.stats.cache_hit_tokens, 0);
        assert!(prefill.inserted_handle.is_none());
    }

    #[test]
    fn generate_batch_with_prompt() {
        let mut engine = VeloEngine::new(EngineConfig {
            draft_window: 1,
            memory: MemoryRuntimeConfig::cpu(16, 16, 32, 1, 32),
            kv_type: KvCacheType::Fp32,
        }).unwrap();
        let mut draft = ScriptedDraft { script: vec![1, 2], bound_prefixes: vec![], bound_slots: vec![] };
        let mut target = ScriptedTarget { script: vec![1, 2], bound_prefixes: vec![], bound_slots: vec![] };
       
        let outputs = engine.generate(&mut draft, &mut target, &[1], 1).unwrap();
        assert_eq!(outputs.tokens.len(), 1);
    }
}
